/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estatisticas;

import DB.ConnectMYSQL;
import Funcionarios.modeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author luiz
 */
public class telaFecharPedido extends javax.swing.JInternalFrame {

    ConnectMYSQL conex = new ConnectMYSQL();
    beansEstatisticaPedidos mod = new beansEstatisticaPedidos();
    daoEstatisticaPesquisa control = new daoEstatisticaPesquisa();
    
    
    
    public telaFecharPedido() {
        initComponents();
        preencherTabelaPedidos("select *from compra order by data");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jTextFieldPesquisar = new javax.swing.JTextField();

        setClosable(true);

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePedidos);

        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(jTextFieldPesquisar.getText());
        control.buscar(mod);
        preencherTabelaPedidos("select *from compra where nome like'%" + mod.getPesquisa()+ "%'");
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    public void preencherTabelaPedidos(String Sql){
          ArrayList dados = new ArrayList();
          String [] colunas = new String []{"ID","Nome","Valor","Quantidade","Data"};
          conex.conectar();
          conex.executaSql(Sql);        
          try{
              conex.rs.first();
              do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getString("valor"),conex.rs.getDouble("quantidade"),conex.rs.getString("data")});
              }while(conex.rs.next());
          }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Erro ao preencher Arraylist"+ex); 
          }
          modeloTabela modelo = new modeloTabela(dados, colunas);
          
          jTablePedidos.setModel(modelo);
          jTablePedidos.getColumnModel().getColumn(0).setPreferredWidth(43);
          jTablePedidos.getColumnModel().getColumn(0).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(1).setPreferredWidth(121);
          jTablePedidos.getColumnModel().getColumn(1).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(2).setPreferredWidth(90);
          jTablePedidos.getColumnModel().getColumn(2).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(3).setPreferredWidth(85);
          jTablePedidos.getColumnModel().getColumn(3).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(4).setPreferredWidth(85);
          jTablePedidos.getColumnModel().getColumn(4).setResizable(false);

          jTablePedidos.getTableHeader().setReorderingAllowed(false);
          jTablePedidos.setAutoResizeMode(jTablePedidos.AUTO_RESIZE_OFF);
          jTablePedidos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.desconecta();
      }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
