/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcionarios;

/**
 *
 * @author luiz
 */

import DB.ConnectMYSQL;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
public class telaGerenciarFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaGerenciasFuncionarios1
     */
    beansFuncionarios mod = new beansFuncionarios();
    daoFuncionarios control = new daoFuncionarios();
    ConnectMYSQL conex = new ConnectMYSQL();
    int flag;
    
    public void atualizarTabela() {
             while (true) {
                try {
                         mod.setPesquisa(jTextFieldPesquisar.getText());
                         mod.setTipoPesquisa((String) jComboBox1.getSelectedItem());
                         control.buscar(mod);
                         if(jTextFieldPesquisar.getText().equals("")){
                             preencherTabela("select *from funcionarios order by usuario");
                         }else{
                         
                        preencherTabela("select *from funcionarios where usuario like'%" + mod.getPesquisa()+ "%'"+"and cargo like'"+mod.getTipoPesquisa()+"'"); 
                         }
                         
                         
                         
                    Thread.sleep(20000);
             } catch (InterruptedException ex) {
        Thread.currentThread().interrupt();
      }
    }
  }
    
    
    public telaGerenciarFuncionarios() {
        initComponents();
        new Thread(new Runnable() {
            @Override
            public void run() {
            atualizarTabela();
            }
        }).start();    
        
    }
    
    public void habilitarBotoes(){
        jButtonDeletar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        
    }
    public void desabilitarBotoes(){
        jButtonDeletar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
    }
    public void liberarCampos(){
        jTextFieldNome.setEnabled(true);
        jTextFieldSenha.setEnabled(true);
        jTextFieldSenha2.setEnabled(true);
        jComboBox.setEnabled(true);
        jTextField_NomeCompleto.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jComboBoxBairros.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        
        jTextFieldNome.setText("Usuário");
        jFormattedTextFieldTelefone.setText("");
        jTextField_NomeCompleto.setText("Nome Completo");
        jComboBox.setSelectedItem("Administrador");
        jTextFieldSenha.setText("Senha");
        jTextFieldSenha2.setText("Confirmar Senha");
        jTextFieldEmail.setText("Email");
        jTextFieldRua.setText("Rua do Funcionário");
        jComboBox.setSelectedItem("Abolição");
        jFormattedTextFieldCPF.setText("");
        
        
    }
    public void bloquearCampos(){
        jTextFieldNome.setEnabled(false);
        jTextFieldSenha.setEnabled(false);
        jTextFieldSenha2.setEnabled(false);
        jComboBox.setEnabled(false);
        jTextField_NomeCompleto.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jTextFieldRua.setEnabled(false);
        jComboBoxBairros.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        
        jTextFieldNome.setText("Usuário");
        jFormattedTextFieldTelefone.setText("");
        jTextField_NomeCompleto.setText("Nome Completo");
        jComboBox.setSelectedItem("Administrador");
        jTextFieldSenha.setText("Senha");
        jTextFieldSenha2.setText("Confirmar Senha");
        jTextFieldEmail.setText("Email");
        jTextFieldRua.setText("Rua do Funcionário");
        jComboBox.setSelectedItem("Abolição");
        jFormattedTextFieldCPF.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jTextFieldSenha = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldSenha2 = new javax.swing.JTextField();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jTextField_NomeCompleto = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldRua = new javax.swing.JTextField();
        jComboBoxBairros = new javax.swing.JComboBox<>();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciar Funcionarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jComboBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Funcionario" }));
        jComboBox.setEnabled(false);
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox);
        jComboBox.setBounds(10, 60, 340, 40);

        jTableUsuarios.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 1310, 370);

        jTextFieldSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSenha.setText("Senha");
        jTextFieldSenha.setEnabled(false);
        jTextFieldSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSenhaMouseClicked(evt);
            }
        });
        jTextFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldSenha);
        jTextFieldSenha.setBounds(360, 60, 410, 40);

        jTextFieldNome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldNome.setText("Usuário");
        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNomeMouseClicked(evt);
            }
        });
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(10, 10, 350, 40);

        jTextFieldSenha2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSenha2.setText("Confirmar Senha");
        jTextFieldSenha2.setEnabled(false);
        jTextFieldSenha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSenha2MouseClicked(evt);
            }
        });
        jTextFieldSenha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSenha2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldSenha2);
        jTextFieldSenha2.setBounds(780, 60, 530, 40);

        jTextFieldPesquisar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(10, 200, 1070, 40);

        jButtonSalvar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(600, 160, 360, 32);

        jButtonDeletar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeletar);
        jButtonDeletar.setBounds(310, 160, 280, 32);

        jTextFieldId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldId.setEnabled(false);
        jPanel1.add(jTextFieldId);
        jTextFieldId.setBounds(1270, 110, 40, 40);

        jButtonEditar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(970, 160, 340, 32);

        jTextField_NomeCompleto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_NomeCompleto.setText("Nome Completo");
        jTextField_NomeCompleto.setEnabled(false);
        jTextField_NomeCompleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_NomeCompletoMouseClicked(evt);
            }
        });
        jTextField_NomeCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_NomeCompletoKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_NomeCompleto);
        jTextField_NomeCompleto.setBounds(750, 10, 560, 40);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Funcionario" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(1090, 200, 230, 40);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setToolTipText("");
        jFormattedTextFieldCPF.setEnabled(false);
        jFormattedTextFieldCPF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(1080, 110, 180, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Telefone:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 20, 100, 22);

        jButtonNovo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(10, 160, 290, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("CPF:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1020, 120, 50, 20);

        jTextFieldEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldEmail.setText("Email");
        jTextFieldEmail.setEnabled(false);
        jTextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMouseClicked(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(10, 110, 340, 40);

        jTextFieldRua.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldRua.setText("Rua do Funcionário");
        jTextFieldRua.setEnabled(false);
        jTextFieldRua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRuaMouseClicked(evt);
            }
        });
        jTextFieldRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRuaKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldRua);
        jTextFieldRua.setBounds(360, 110, 370, 40);

        jComboBoxBairros.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxBairros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abolição", "Acari", "Água Santa", "Alto da Boa Vista", "Anchieta", "Andaraí", "Anil", "Araújo Cosmos", "Baía Guanabara", "Bancários", "Bangu", "Barra da Tijuca", "Barra de Guaratiba", "Barra Guaratiba", "Barros Filho", "Benfica", "Bento Ribeiro", "Bonsucesso", "Botafogo", "Braz de Pina", "Braz Pina", "Cachambi", "Cacuia", "Caju", "Camorim", "Campinho", "Campo dos Afonsos", "Campo Grande", "Cascadura", "Catete", "Catumbi", "Cavalcanti", "Centro", "Cidade de Deus", "Cidade Deus", "Cidade Nova", "Cidade Universitária", "Cocota", "Coelho Neto", "Colégio", "Copacabana", "Cordovil", "Cosme Velho", "Cosmos", "Costa Barros", "Curicica", "Curral Falso", "Delegado Castilho", "Dendê", "Deodoro", "Dumas", "Encantado", "Engenheiro Leal", "Engenho da Rainha", "Engenho de Dentro", "Engenho Novo", "Estácio", "Flamengo", "Freguesia", "Freguesia - Ilha Governador", "Freguesia - Jacarepaguá", "Galeão", "Gamboa", "Gardênia Azul", "Gávea", "Glória", "Grajaú", "Guadalupe", "Guarabu", "Guaratiba", "Higienópolis", "Honório Gurgel", "Humaitá", "Inhaúma", "Inhoaíba", "Ipanema", "Irajá", "Itacolomi", "Itanhangá", "Jacaré", "Jacarepaguá", "Jardim América", "Jardim Botânico", "Jardim Carioca", "Jardim Guanabara", "Jardim Sulacap", "Joa", "Lagoa", "Laranjeiras", "Leblon", "Leme", "Lins de Vasconcelos", "Lins Vasconcelos", "Loteamento Madean", "Madureira", "Magalhães Bastos", "Mangueira", "Manguinhos", "Maracanã", "Mare", "Marechal Hermes", "Maria da Graça", "Meier", "Moneró", "Nossa Senhora das Graças", "Nossa Senhora Graças", "Olaria", "Oswaldo Cruz", "Paciência", "Padre Miguel", "Paquetá", "Parada de Lucas", "Parada Lucas", "Parque Anchieta", "Parque Boa Esperança", "Pavuna", "Pechincha", "Pedra de Guaratiba", "Pedra Guaratiba", "Penha", "Penha Circular", "Piedade", "Pilares", "Pitangueiras", "Portuguesa", "Praça Bandeira", "Praça Seca", "Praia Bandeira", "Quintino Bocaiuva", "Ramos", "Realengo", "Recreio Bandeirantes", "Recreio dos Bandeirantes", "Riachuelo", "Ribeira", "Ricardo de Albuquerque", "Rio Comprido", "Rocha", "Rocha Miranda", "Rocinha", "Sampaio", "Santa Cruz", "Santa Teresa", "Santa Tereza", "Santíssimo", "Santo Cristo", "São Conrado", "São Cristóvão", "São Francisco Xavier", "Saúde", "Senador Camará", "Senador Vasconcelos", "Sepetiba", "Tanque", "Taquara", "Tauá", "Tijuca", "Todos Os Santos", "Tomás Coelho", "Tubiacanga", "Turiaçu", "Urca", "Vargem Grande", "Vargem Pequena", "Vaz Lobo", "Vicente de Carvalho", "Vidigal", "Vigário Geral", "Vila da Penha", "Vila Isabel", "Vila Kosmos", "Vila Militar", "Vila Penha", "Vila Valqueire", "Vista Alegre", "Zumbi" }));
        jComboBoxBairros.setEnabled(false);
        jPanel1.add(jComboBoxBairros);
        jComboBoxBairros.setBounds(750, 110, 260, 40);

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setToolTipText("");
        jFormattedTextFieldTelefone.setEnabled(false);
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jFormattedTextFieldTelefone);
        jFormattedTextFieldTelefone.setBounds(470, 10, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NomeCompletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_NomeCompletoMouseClicked
        if(jTextField_NomeCompleto.getText().equals("Nome Completo")){
            jTextField_NomeCompleto.setText("");
        }
    }//GEN-LAST:event_jTextField_NomeCompletoMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldSenha.setEnabled(true);
        jTextFieldSenha2.setEnabled(true);
        jComboBox.setEnabled(true);
        jTextField_NomeCompleto.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jComboBoxBairros.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        
        habilitarBotoes();
        jTextFieldSenha2.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
                int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta ==JOptionPane.YES_OPTION){
            mod.setId(Integer.parseInt(jTextFieldId.getText()));
            control.excluir(mod);
            preencherTabela("select *from funcionarios order by usuario");
            desabilitarBotoes();
            bloquearCampos();
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

if(jTextFieldNome.getText().equals("Usuário") || jTextFieldSenha.getText().equals("senha")){
    JOptionPane.showMessageDialog(null, "Por medidas de segurança usúario nao pode ser igual à Usuário e senha não pode ser igual à senha");
}else{
        if(flag ==1){
            if(jTextFieldSenha.getText().equals(jTextFieldSenha2.getText())){
                mod.setUsuario(jTextFieldNome.getText());
                mod.setSenha(jTextFieldSenha.getText());
                mod.setCargo((String) jComboBox.getSelectedItem());
                mod.setRamal(Integer.parseInt(jFormattedTextFieldTelefone.getText()));
                mod.setNomeCompleto(jTextField_NomeCompleto.getText());
                mod.setEmail(jTextFieldEmail.getText());
                mod.setRua(jTextFieldRua.getText());
                mod.setBairro((String) jComboBoxBairros.getSelectedItem());
                mod.setCpf(Long.parseLong(jFormattedTextFieldCPF.getText()));
                //
                control.Salvar(mod);
                bloquearCampos();
                desabilitarBotoes();
                preencherTabela("select * from funcionarios order by usuario");
            } else {
                JOptionPane.showMessageDialog(null, "As senhas não correspondem");
            }
        } else {
            mod.setUsuario(jTextFieldNome.getText());
            mod.setSenha(jTextFieldSenha.getText());
            mod.setCargo((String) jComboBox.getSelectedItem());
            mod.setRamal(Integer.parseInt(jFormattedTextFieldTelefone.getText()));
            mod.setNomeCompleto(jTextField_NomeCompleto.getText());
            mod.setEmail(jTextFieldEmail.getText());
            mod.setRua(jTextFieldRua.getText());
            mod.setBairro((String) jComboBoxBairros.getSelectedItem());
            mod.setCpf(Long.parseLong(jFormattedTextFieldCPF.getText()));
            mod.setId(Integer.parseInt(jTextFieldId.getText()));
            control.editar(mod);
            bloquearCampos();
            desabilitarBotoes();
            preencherTabela("select *from funcionarios order by usuario");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        if(!jTextFieldPesquisar.getText().equals("")){
       
        mod.setPesquisa(jTextFieldPesquisar.getText());
        mod.setTipoPesquisa((String) jComboBox1.getSelectedItem());
        control.buscar(mod);
         preencherTabela("select *from funcionarios where usuario like'%" + mod.getPesquisa()+ "%'"+"and cargo like'"+mod.getTipoPesquisa()+"'"); 
            
        }
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldSenha2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSenha2KeyPressed
        if(jTextFieldSenha2.getText().equals("Confirmar Senha")){
            jTextFieldSenha2.setText("");
        }
    }//GEN-LAST:event_jTextFieldSenha2KeyPressed

    private void jTextFieldSenha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSenha2MouseClicked
        if(jTextFieldSenha2.getText().equals("Confirmar Senha")){
            jTextFieldSenha2.setText("");
        }
    }//GEN-LAST:event_jTextFieldSenha2MouseClicked

    private void jTextFieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyPressed
        if(jTextFieldNome.getText().equals("Usuário")){
            jTextFieldNome.setText("");
        }
    }//GEN-LAST:event_jTextFieldNomeKeyPressed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNomeMouseClicked
        if(jTextFieldNome.getText().equals("Usuário")){
            jTextFieldNome.setText("");
        }
    }//GEN-LAST:event_jTextFieldNomeMouseClicked

    private void jTextFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSenhaKeyPressed
        if(jTextFieldSenha.getText().equals("Senha")){
            jTextFieldSenha.setText("");
        }
    }//GEN-LAST:event_jTextFieldSenhaKeyPressed

    private void jTextFieldSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSenhaMouseClicked
        if(jTextFieldSenha.getText().equals("Senha")){
            jTextFieldSenha.setText("");
        }
    }//GEN-LAST:event_jTextFieldSenhaMouseClicked

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        String usuario =""+jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 1);
        conex.conectar();
        conex.executaSql("select *from funcionarios where usuario='"+usuario+"'");
        try {
            conex.rs.first();
            jTextFieldId.setText(String.valueOf(conex.rs.getInt("id")));
            jTextFieldNome.setText(conex.rs.getString("usuario"));
            jTextFieldSenha.setText(conex.rs.getString("senha"));
            jComboBox.setSelectedItem(conex.rs.getString("cargo"));
            jFormattedTextFieldTelefone.setText(String.valueOf(conex.rs.getInt("ramal")));
            jFormattedTextFieldCPF.setText(String.valueOf(conex.rs.getLong("cpf")));
            jTextField_NomeCompleto.setText(conex.rs.getString("nomecompleto"));

            desabilitarBotoes();
            
       

            jButtonDeletar.setEnabled(true);
            jButtonEditar.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados "+ex);
        }

        conex.desconecta();
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jTextField_NomeCompletoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NomeCompletoKeyPressed
        // TODO add your handling code here:
        if(jTextField_NomeCompleto.getText().equals("Nome Completo")){
            jTextField_NomeCompleto.setText("");
        }
    }//GEN-LAST:event_jTextField_NomeCompletoKeyPressed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        habilitarBotoes();
        liberarCampos();
        flag =1;
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMouseClicked
        // TODO add your handling code here:
        if(jTextFieldEmail.getText().equals("Email")){
            jTextFieldEmail.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmailMouseClicked

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
        // TODO add your handling code here:
        if(jTextFieldEmail.getText().equals("Email")){
            jTextFieldEmail.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jTextFieldRuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRuaMouseClicked
        // TODO add your handling code here:
        if(jTextFieldRua.getText().equals("Rua do Funcionário")){
            jTextFieldRua.setText("");
        }
    }//GEN-LAST:event_jTextFieldRuaMouseClicked

    private void jTextFieldRuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRuaKeyPressed
        // TODO add your handling code here:
         if(jTextFieldRua.getText().equals("Rua do Funcionário")){
            jTextFieldRua.setText("");
        }
    }//GEN-LAST:event_jTextFieldRuaKeyPressed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
         mod.setPesquisa(jTextFieldPesquisar.getText());
         mod.setTipoPesquisa((String) jComboBox1.getSelectedItem());
        control.buscar(mod);
        
            mod.setPesquisa(jTextFieldPesquisar.getText());
            mod.setTipoPesquisa((String) jComboBox1.getSelectedItem());
            control.buscar(mod);
             preencherTabela("select *from funcionarios where usuario like'%" + mod.getPesquisa()+ "%'"+"and cargo like'"+mod.getTipoPesquisa()+"'"); 
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
         public void preencherTabela(String Sql){
          ArrayList dados = new ArrayList();
          String [] colunas = new String []{"ID","Usuario","Senha","Cargo","Ramal","Nome Completo","Email","Rua","Bairro","CPF"};
          conex.conectar();
          conex.executaSql(Sql);        
          try{
              conex.rs.first();
              do{
                  dados.add(new Object[] { conex.rs.getInt("id"),conex.rs.getString("usuario"),conex.rs.getString("senha"),conex.rs.getString("cargo"),conex.rs.getString("ramal"),conex.rs.getString("nomecompleto"),conex.rs.getString("email"),conex.rs.getString("rua"),conex.rs.getString("bairro"),conex.rs.getString("cpf") });
              }while(conex.rs.next());
          }catch(SQLException ex){
              
              
          }
          modeloTabela modelo = new modeloTabela(dados, colunas);
          
          jTableUsuarios.setModel(modelo);
          jTableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(40);
          jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(1).setPreferredWidth(250);
          jTableUsuarios.getColumnModel().getColumn(1).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(2).setPreferredWidth(250);
          jTableUsuarios.getColumnModel().getColumn(2).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(3).setPreferredWidth(250);
          jTableUsuarios.getColumnModel().getColumn(3).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(4).setPreferredWidth(150);
          jTableUsuarios.getColumnModel().getColumn(4).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(5).setPreferredWidth(364);
          jTableUsuarios.getColumnModel().getColumn(5).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(6).setPreferredWidth(250);
          jTableUsuarios.getColumnModel().getColumn(6).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(7).setPreferredWidth(250);
          jTableUsuarios.getColumnModel().getColumn(7).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(8).setPreferredWidth(250);
          jTableUsuarios.getColumnModel().getColumn(8).setResizable(false);
          jTableUsuarios.getColumnModel().getColumn(9).setPreferredWidth(150);
          jTableUsuarios.getColumnModel().getColumn(9).setResizable(false);

          jTableUsuarios.getTableHeader().setReorderingAllowed(false);
          jTableUsuarios.setAutoResizeMode(jTableUsuarios.AUTO_RESIZE_OFF);
          jTableUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.desconecta();
      }
         
         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxBairros;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JTextField jTextFieldSenha2;
    private javax.swing.JTextField jTextField_NomeCompleto;
    // End of variables declaration//GEN-END:variables
}
