/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pedidos;

import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Felipe
 */
public class dataDasParcelas extends javax.swing.JFrame {

    int numeroDeParcelas;
    private int  numeroParcelaAtual = 0;
    
    double valorAtual;
    double preçoPorParcela;
    double valorTotalRestante;
    double valorTotal;
   
    
    beansParcela mod = new beansParcela();
    daoParcelas dao = new daoParcelas();
    
    public dataDasParcelas(int parcelado, String nome, double valorAtual) {
        initComponents();
        numeroDeParcelas = parcelado;
        this.valorAtual = valorAtual;
        valorTotal = valorAtual;
        double preçoPorParcela = Double.valueOf(String.format(Locale.US, "%.2f", valorTotal/parcelado));

        this.preçoPorParcela = preçoPorParcela;
         mod.setNome(nome);
         mod.setValor(preçoPorParcela); 
         mod.setValorTotal(valorTotal);
     
    }

    private dataDasParcelas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Parcela Numero 1");

        jCalendar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Próximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    
         addNumeroAtual();
        String formatarDate = new SimpleDateFormat("dd/MM/yyyy").format(jCalendar1.getDate()); 
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(null, "Realmente deseja marcar a parcela de número "+getNumeroParcelaAtual()+" para " + formatarDate +"?"+"\nApós aceitar você só poderá mudar na tela de entregas e parcelas");
        if(resposta ==JOptionPane.YES_OPTION){

        
        
            if(jButton1.getText().equals("Próximo")){
                    if( getNumeroParcelaAtual() < numeroDeParcelas -1){

                        jLabel1.setText("Parcela Número "+  getNumeroParcelaAtual());
                            mod.setParcelaNum(getNumeroParcelaAtual());
                            mod.setData(formatarDate);
                            System.out.println(getNumeroParcelaAtual() + "   -   " + preçoPorParcela);
                            valorTotalRestante = Double.valueOf(String.format(Locale.US, "%.2f", valorAtual - (numeroParcelaAtual * preçoPorParcela)));                         
                            mod.setValorTotalRestante(valorTotalRestante);                     
                            dao.Salvar(mod);                            
                            
                         
                    }else if(getNumeroParcelaAtual()  == numeroDeParcelas -1){
                         jLabel1.setText("Parcela Número "+  getNumeroParcelaAtual());
                         jButton1.setText("Finalizar");
                            mod.setParcelaNum(getNumeroParcelaAtual());
                            mod.setData(formatarDate);
                            valorTotalRestante = Double.valueOf(String.format(Locale.US, "%.2f", valorAtual - (numeroParcelaAtual * preçoPorParcela)));  
                            mod.setValorTotalRestante(valorTotalRestante);                                                          
                            dao.Salvar(mod);                            
                    }     
            }else{
                 mod.setParcelaNum(getNumeroParcelaAtual());
                 mod.setData(formatarDate);
                 valorTotalRestante = Double.valueOf(String.format(Locale.US, "%.2f", valorAtual - (numeroParcelaAtual * preçoPorParcela)));  
                 mod.setValorTotalRestante(0);                         
             
                 dao.Salvar(mod);
                dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataDasParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataDasParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataDasParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataDasParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataDasParcelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the numeroParcelaAtual
     */
    public int getNumeroParcelaAtual() {
        return numeroParcelaAtual;
    }

    /**
     * @param numeroParcelaAtual the numeroParcelaAtual to set
     */
    public void addNumeroAtual() {
        this.numeroParcelaAtual ++;
    }


}
