/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Produtos;

import DB.ConnectMYSQL;
import Funcionarios.modeloTabela;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Timer;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author luiz
 */
public class telaEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaEstoque
     */
    ConnectMYSQL conex = new ConnectMYSQL();
    beansProdutos mod = new beansProdutos();
    daoProdutos dao = new daoProdutos();
    int x = 1;

    public telaEstoque() throws InterruptedException {
        initComponents();
        while(x == 1){
            sleep(1000);
            preencherTabela("select *from produtos order by nome");
        }
        
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstoqueProdutos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jComboBoxTipoDoProduto = new javax.swing.JComboBox<>();

        setBorder(null);

        jTableEstoqueProdutos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTableEstoqueProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableEstoqueProdutos);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Adicionar Quantidade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });

        jComboBoxTipoDoProduto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxTipoDoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Hidráulicos", "Ferragens e Ferramentas", "Tubos", "Fabricantes", "Tintas e Abrasivos", "Ferramentas Manuais", "Material Elétrico" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1736, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       if(jTableEstoqueProdutos.getSelectedRow() != -1){  
        String perguntaQuantidade;
        perguntaQuantidade = JOptionPane.showInputDialog(null, "Qual a quantidade?", JOptionPane.PLAIN_MESSAGE);        
        int quantidade = new Integer(perguntaQuantidade);
        
        mod.setId((int) jTableEstoqueProdutos.getValueAt(jTableEstoqueProdutos.getSelectedRow(), 0));
        mod.setNome((String) jTableEstoqueProdutos.getValueAt(jTableEstoqueProdutos.getSelectedRow(), 1));
        mod.setTipo((String) jTableEstoqueProdutos.getValueAt(jTableEstoqueProdutos.getSelectedRow(), 2));
        mod.setValor((Double) jTableEstoqueProdutos.getValueAt(jTableEstoqueProdutos.getSelectedRow(), 3));
        mod.setEstoque((int) jTableEstoqueProdutos.getValueAt(jTableEstoqueProdutos.getSelectedRow(), 4) + quantidade);
        dao.editar(mod);
        preencherTabela("select *from produtos order by nome");

       }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        mod.setPesquisa(jTextFieldPesquisar.getText());
        mod.setTipoPesquisa((String) jComboBoxTipoDoProduto.getSelectedItem());
        dao.buscar(mod);
        if(jComboBoxTipoDoProduto.getSelectedItem() == "Todos"){
            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'");
        }else{
            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'"+"and tipo like'"+mod.getTipoPesquisa()+"'");
        }
        
        
        
        
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    

    public void preencherTabela(String Sql){
          ArrayList dados = new ArrayList();
          String [] colunas = new String []{"ID","Nome","Tipo","Valor","Estoque"};
          conex.conectar();
          conex.executaSql(Sql);        
          try{
              conex.rs.first();
              do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getString("tipo"),conex.rs.getDouble("valor"),conex.rs.getInt("estoque")});
              }while(conex.rs.next());
          }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Erro ao preencher Arraylist"+ex); 
          }
          modeloTabela modelo = new modeloTabela(dados, colunas);
          
          jTableEstoqueProdutos.setModel(modelo);
          jTableEstoqueProdutos.getColumnModel().getColumn(0).setPreferredWidth(70);
          jTableEstoqueProdutos.getColumnModel().getColumn(0).setResizable(false);
          jTableEstoqueProdutos.getColumnModel().getColumn(1).setPreferredWidth(315);
          jTableEstoqueProdutos.getColumnModel().getColumn(1).setResizable(false);
          jTableEstoqueProdutos.getColumnModel().getColumn(2).setPreferredWidth(315);
          jTableEstoqueProdutos.getColumnModel().getColumn(2).setResizable(false);
          jTableEstoqueProdutos.getColumnModel().getColumn(3).setPreferredWidth(315);
          jTableEstoqueProdutos.getColumnModel().getColumn(3).setResizable(false);
          jTableEstoqueProdutos.getColumnModel().getColumn(4).setPreferredWidth(315);
          jTableEstoqueProdutos.getColumnModel().getColumn(4).setResizable(false);
          jTableEstoqueProdutos.getTableHeader().setReorderingAllowed(false);
          jTableEstoqueProdutos.setAutoResizeMode(jTableEstoqueProdutos.AUTO_RESIZE_OFF);
          jTableEstoqueProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.desconecta();
      }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxTipoDoProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstoqueProdutos;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
