/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Produtos;

import javax.swing.JOptionPane;

/**
 *
 * @author luiz
 */
    import DB.ConnectMYSQL;
    import Funcionarios.modeloTabela;
import imprimir.imprimir;
    import java.sql.SQLException;
    import java.util.ArrayList;
    import javax.swing.JOptionPane;
    import javax.swing.ListSelectionModel;

public class telaGenrenciarProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaGenrenciarProdutosi
     */
            beansProdutos mod = new beansProdutos();
            daoProdutos control = new daoProdutos();
            ConnectMYSQL conex = new ConnectMYSQL();
            
            int flag = 1;
            
             public void atualizarTabela() {
             while (true) {                 
                try {
                   
                    
                    mod.setPesquisa(jTextFieldPesquisa.getText());
                    mod.setTipoPesquisa((String) jComboBoxTipodoProduto.getSelectedItem());
                    control.buscar(mod);
                    populaComboBox();
                     if(jComboBoxTipodoProduto.getSelectedItem() == "Todos"){
                        if(jTextFieldPesquisa.getText().equals("")){
                            preencherTabela("select *from produtos order by nome");
                        }else{
                            mod.setPesquisa(jTextFieldPesquisa.getText());
                            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'");
                            
                        }
                }else{
            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'"+"and tipo like'"+mod.getTipoPesquisa()+"'");
        }
            Thread.sleep(20000);
             } catch (InterruptedException ex) {
        Thread.currentThread().interrupt();
      }
    }
  }
            
            
    public telaGenrenciarProdutos() {
        initComponents();
        new Thread(new Runnable() {
            @Override
            public void run() {
            atualizarTabela();
            }
        }).start();   
        
        populaComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField = new javax.swing.JTextField();
        jTextFieldNomedoProduto = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldPreço = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonEnviar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jComboBoxTipodoProduto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(null);

        jTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField.setEnabled(false);
        getContentPane().add(jTextField);
        jTextField.setBounds(10, 10, 40, 40);

        jTextFieldNomedoProduto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldNomedoProduto.setText("Nome do Produto");
        jTextFieldNomedoProduto.setToolTipText("Nome do Produto");
        jTextFieldNomedoProduto.setEnabled(false);
        jTextFieldNomedoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNomedoProdutoMouseClicked(evt);
            }
        });
        jTextFieldNomedoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomedoProdutoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNomedoProduto);
        jTextFieldNomedoProduto.setBounds(60, 10, 400, 40);

        jTextFieldQuantidade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldQuantidade.setText("Quantidade");
        jTextFieldQuantidade.setToolTipText("Quantidade");
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldQuantidadeMouseClicked(evt);
            }
        });
        jTextFieldQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldQuantidade);
        jTextFieldQuantidade.setBounds(1060, 60, 280, 40);

        jTextFieldPreço.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPreço.setText("R$ 00,00");
        jTextFieldPreço.setToolTipText("Valor");
        jTextFieldPreço.setEnabled(false);
        jTextFieldPreço.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPreçoMouseClicked(evt);
            }
        });
        jTextFieldPreço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreçoActionPerformed(evt);
            }
        });
        jTextFieldPreço.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPreçoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPreço);
        jTextFieldPreço.setBounds(760, 60, 290, 40);

        jLabelTipo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTipo.setText("Tipo:");
        getContentPane().add(jLabelTipo);
        jLabelTipo.setBounds(10, 70, 70, 24);

        jComboBoxTipo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hidráulicos", "Ferragens e Ferramentas", "Tubos", "Fabricantes", "Tintas e Abrasivos", "Ferramentas Manuais", "Material Elétrico" }));
        jComboBoxTipo.setEnabled(false);
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipo);
        jComboBoxTipo.setBounds(70, 60, 310, 40);

        jButtonEnviar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.setEnabled(false);
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar);
        jButtonEnviar.setBounds(1060, 10, 280, 40);

        jButtonDeletar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletar);
        jButtonDeletar.setBounds(760, 10, 290, 40);

        jButtonNovo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(470, 10, 280, 40);

        jTableProdutos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 1330, 430);

        jTextFieldPesquisa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPesquisa.setToolTipText("Pesquisa");
        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(120, 110, 800, 40);

        jComboBoxTipodoProduto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxTipodoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Hidráulicos", "Ferragens e Ferramentas", "Tubos", "Fabricantes", "Tintas e Abrasivos", "Ferramentas Manuais", "Material Elétrico" }));
        jComboBoxTipodoProduto.setToolTipText("Tipo da Pesquisa");
        jComboBoxTipodoProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipodoProdutoItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxTipodoProduto);
        jComboBoxTipodoProduto.setBounds(930, 110, 410, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisa:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 120, 100, 20);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Marca:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 70, 70, 24);

        jComboBoxMarca.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxMarca.setEnabled(false);
        jComboBoxMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMarcaMouseClicked(evt);
            }
        });
        jComboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMarca);
        jComboBoxMarca.setBounds(470, 60, 280, 40);

        jButton1.setText("Imprimir Tabela Produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 590, 1330, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populaComboBox(){
     try{   
        conex.executaSql("select *from marca order by nome");
        while(conex.rs.next()){
            jComboBoxMarca.addItem(conex.rs.getString("nome"));
        }
    }catch(SQLException ex){
        
    }
  }
    
    public void Liberar(){
        
        jTextFieldNomedoProduto.setEnabled(true);
        jTextFieldPreço.setEnabled(true);
        jTextFieldQuantidade.setEnabled(true);
        jComboBoxTipo.setEnabled(true);
        jComboBoxMarca.setEnabled(true);
    }
    
    public void BloquearEscrever(){
        jTextFieldNomedoProduto.setText("Nome do Produto");
        jTextFieldPreço.setText("R$ 00,00");
        jTextFieldQuantidade.setText("Quantidade");
        
        jTextFieldNomedoProduto.setEnabled(false);
        jTextFieldPreço.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jComboBoxTipo.setEnabled(false);
        jComboBoxMarca.setEnabled(false);
    }
    
    
    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        flag = 1;
        Liberar();
        jTextFieldNomedoProduto.setText("Nome do Produto");
        jTextFieldPreço.setText("R$ 00,00");
        jTextFieldQuantidade.setText("Quantidade");
        
        jButtonDeletar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonEnviar.setEnabled(true);
        populaComboBox();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        // TODO add your handling code here:
        int resposta =0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta ==JOptionPane.YES_OPTION){
            mod.setId(Integer.parseInt(jTextField.getText()));
            control.excluir(mod);
            if(jComboBoxTipodoProduto.getSelectedItem() == "Todos"){
                        if(jTextFieldPesquisa.getText().equals("")){
                    preencherTabela("select *from produtos order by nome");
                    populaComboBox();
                    
                        }else{
                            mod.setPesquisa(jTextFieldPesquisa.getText());
                            control.buscar(mod);
                            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'");
                            populaComboBox();
                      }                        
                }else{
                      mod.setPesquisa(jTextFieldPesquisa.getText());
                      mod.setTipoPesquisa((String) jComboBoxTipodoProduto.getSelectedItem());
                      control.buscar(mod);                      
                      preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'"+"and tipo like'"+mod.getTipoPesquisa()+"'");
                      populaComboBox();
                      
        }
            BloquearEscrever();
        }
                       
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        if(flag == 1){
            mod.setNome(jTextFieldNomedoProduto.getText());
            mod.setTipo((String) jComboBoxTipo.getSelectedItem());
            mod.setValor(Double.parseDouble(jTextFieldPreço.getText()));
            
            if(jTextFieldQuantidade.getText().equals("Quantidade") || jTextFieldQuantidade.getText().equals("")){
                 mod.setEstoque(1);
            }else{                        
            mod.setEstoque(Integer.parseInt(jTextFieldQuantidade.getText()));
            }
            
            mod.setMarca((String) jComboBoxMarca.getSelectedItem());
            control.Salvar(mod);
             if(jComboBoxTipodoProduto.getSelectedItem() == "Todos"){
                        if(jTextFieldPesquisa.getText().equals("")){
                    preencherTabela("select *from produtos order by nome");
                    populaComboBox();
                    
                        }else{
                            mod.setPesquisa(jTextFieldPesquisa.getText());
                            control.buscar(mod);
                            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'");
                            populaComboBox();
                      }                        
                }else{
                      mod.setPesquisa(jTextFieldPesquisa.getText());
                      mod.setTipoPesquisa((String) jComboBoxTipodoProduto.getSelectedItem());
                      control.buscar(mod);                      
                      preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'"+"and tipo like'"+mod.getTipoPesquisa()+"'");
                      populaComboBox();
                      
        }
            BloquearEscrever();
        }else{
            mod.setNome(jTextFieldNomedoProduto.getText());
            mod.setTipo((String) jComboBoxTipo.getSelectedItem());
            mod.setValor(Double.parseDouble(jTextFieldPreço.getText()));
            mod.setEstoque(Integer.parseInt(jTextFieldQuantidade.getText()));
            mod.setMarca((String) jComboBoxMarca.getSelectedItem());
            mod.setId(Integer.parseInt(jTextField.getText()));
            control.editar(mod);
            if(jComboBoxTipodoProduto.getSelectedItem() == "Todos"){
                        if(jTextFieldPesquisa.getText().equals("")){
                    preencherTabela("select *from produtos order by nome");
                    
                        }else{
                            mod.setPesquisa(jTextFieldPesquisa.getText());
                            control.buscar(mod);
                            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'");
                      }                        
                }else{
                      mod.setPesquisa(jTextFieldPesquisa.getText());
                      mod.setTipoPesquisa((String) jComboBoxTipodoProduto.getSelectedItem());
                      control.buscar(mod);                      
                      preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'"+"and tipo like'"+mod.getTipoPesquisa()+"'");
                      
        }
      }
            BloquearEscrever();
            jButtonNovo.setEnabled(true);
            jButtonEnviar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked

        // TODO add your handling code here:
        String nome =""+jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 1);
        conex.conectar();
        conex.executaSql("select *from produtos where nome='"+nome+"'");
        try {
            flag = 2;
            jButtonNovo.setEnabled(true);
            jButtonEnviar.setEnabled(true);
            jButtonDeletar.setEnabled(true);
            Liberar();
            conex.rs.first();
            jTextField.setText(String.valueOf(conex.rs.getInt("id")));
            jTextFieldNomedoProduto.setText(conex.rs.getString("nome"));
            jComboBoxTipo.setSelectedItem(conex.rs.getString("tipo"));
            jComboBoxMarca.setSelectedItem(conex.rs.getString("marca"));
            jTextFieldPreço.setText(conex.rs.getString("valor"));
            jTextFieldQuantidade.setText(conex.rs.getString("estoque"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados "+ex);
        }

        conex.desconecta();
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void jTextFieldPreçoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPreçoMouseClicked
        // TODO add your handling code here:
        if(jTextFieldPreço.getText().equals("R$ 00,00")){
            jTextFieldPreço.setText("");
        }
    }//GEN-LAST:event_jTextFieldPreçoMouseClicked

    private void jTextFieldPreçoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPreçoKeyPressed
        // TODO add your handling code here:
         if(jTextFieldPreço.getText().equals("R$ 00,00")){
            jTextFieldPreço.setText("");
        }
    }//GEN-LAST:event_jTextFieldPreçoKeyPressed

    private void jTextFieldQuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeMouseClicked
        // TODO add your handling code here:
        if(jTextFieldQuantidade.getText().equals("Quantidade")){
            jTextFieldQuantidade.setText("");
        }
    }//GEN-LAST:event_jTextFieldQuantidadeMouseClicked

    private void jTextFieldQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeKeyPressed
        // TODO add your handling code here:
        if(jTextFieldQuantidade.getText().equals("Quantidade")){
            jTextFieldQuantidade.setText("");
        }
    }//GEN-LAST:event_jTextFieldQuantidadeKeyPressed

    private void jTextFieldNomedoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNomedoProdutoMouseClicked
        // TODO add your handling code here:
        if(jTextFieldNomedoProduto.getText().equals("Nome do Produto")){
            jTextFieldNomedoProduto.setText("");
        }
    }//GEN-LAST:event_jTextFieldNomedoProdutoMouseClicked

    private void jTextFieldNomedoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomedoProdutoKeyPressed
        // TODO add your handling code here:
        if(jTextFieldNomedoProduto.getText().equals("Nome do Produto")){
            jTextFieldNomedoProduto.setText("");
        }
    }//GEN-LAST:event_jTextFieldNomedoProdutoKeyPressed

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(jTextFieldPesquisa.getText());
        mod.setTipoPesquisa((String) jComboBoxTipodoProduto.getSelectedItem());
        control.buscar(mod);
        populaComboBox();
         if(jComboBoxTipodoProduto.getSelectedItem() == "Todos"){
                        if(jTextFieldPesquisa.getText().equals("")){
                    preencherTabela("select *from produtos order by nome");
                        }else{
                            mod.setPesquisa(jTextFieldPesquisa.getText());
                            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'");
                            
                        }
                }else{
            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'"+"and tipo like'"+mod.getTipoPesquisa()+"'");
        }
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jComboBoxTipodoProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipodoProdutoItemStateChanged
        // TODO add your handling code here:
        mod.setPesquisa(jTextFieldPesquisa.getText());
        mod.setTipoPesquisa((String) jComboBoxTipodoProduto.getSelectedItem());
        control.buscar(mod);
         if(jComboBoxTipodoProduto.getSelectedItem() == "Todos"){
                        if(jTextFieldPesquisa.getText().equals("")){
                    preencherTabela("select *from produtos order by nome");
                        }else{
                            mod.setPesquisa(jTextFieldPesquisa.getText());
                            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'");
                            
                        }
                }else{
            preencherTabela("select *from produtos where nome like'%" + mod.getPesquisa()+ "%'"+"and tipo like'"+mod.getTipoPesquisa()+"'");
        }
    }//GEN-LAST:event_jComboBoxTipodoProdutoItemStateChanged

    private void jTextFieldPreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreçoActionPerformed

    private void jComboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcaActionPerformed

    private void jComboBoxMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMarcaMouseClicked
        // TODO add your handling code here:
        populaComboBox();
    }//GEN-LAST:event_jComboBoxMarcaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        imprimir imprimir = new imprimir();
        imprimir.excelTabela(jTableProdutos);
    }//GEN-LAST:event_jButton1ActionPerformed

public void preencherTabela(String Sql){
          ArrayList dados = new ArrayList();
          String [] colunas = new String []{"ID","Nome","Tipo","Marca","Valor","Estoque"};
          conex.conectar();
          conex.executaSql(Sql);        
          try{
              conex.rs.first();
              do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getString("tipo"),conex.rs.getString("marca"),conex.rs.getDouble("valor"),conex.rs.getInt("estoque")});
              }while(conex.rs.next());
          }catch(SQLException ex){
              //JOptionPane.showMessageDialog(null, "Erro ao preencher Arraylist"+ex); 
          }
          modeloTabela modelo = new modeloTabela(dados, colunas);
          
          jTableProdutos.setModel(modelo);
          jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(70);
          jTableProdutos.getColumnModel().getColumn(0).setResizable(false);
          jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(298);
          jTableProdutos.getColumnModel().getColumn(1).setResizable(false);
          jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(248);
          jTableProdutos.getColumnModel().getColumn(2).setResizable(false);
          jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(248);
          jTableProdutos.getColumnModel().getColumn(3).setResizable(false);
          jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(248);
          jTableProdutos.getColumnModel().getColumn(4).setResizable(false);
          jTableProdutos.getColumnModel().getColumn(5).setPreferredWidth(212);            
          jTableProdutos.getColumnModel().getColumn(5).setResizable(false);
          jTableProdutos.getTableHeader().setReorderingAllowed(false);
          jTableProdutos.setAutoResizeMode(jTableProdutos.AUTO_RESIZE_OFF);
          jTableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.desconecta();
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JComboBox<String> jComboBoxTipodoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTextField jTextFieldNomedoProduto;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldPreço;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
