/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pedidos.fecharPedido;

import DB.ConnectMYSQL;
import Funcionarios.modeloTabela;
import Pedidos.beansParcela;
import Pedidos.beansPedido;
import Pedidos.daoParcelas;
import Pedidos.daoPedidos;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author luiz
 */
public class telaFecharPedido extends javax.swing.JInternalFrame {

    ConnectMYSQL conex = new ConnectMYSQL();
    beansPedido mod = new beansPedido();
    daoPedidos control = new daoPedidos();
    
    beansParcela modParcela = new beansParcela();
    daoParcelas daoParcela = new daoParcelas();
    
    public void atualizarTabela() {
             while (true) {                 
                try {

                        if(jTextFieldPesquisar.getText().equals("")){
                    preencherTabelaPedidos("select *from compra order by data");
                    
                        }else{
                            mod.setPesquisa(jTextFieldPesquisar.getText());
                            control.Buscar(mod);
                            preencherTabelaPedidos("select *from compra where nome like'%" + mod.getPesquisa()+ "%'");
                      }
                        
                      if(jTextFieldPesquisarParcela.getText().equals("")){
                          preencherTabelaParcelas("select *from parcelas order by data");
                      }else{
                          modParcela.setBuscar(jTextFieldPesquisarParcela.getText());
                          daoParcela.Buscar(modParcela);
                          preencherTabelaParcelas("select *from parcelas where nome like '%" + modParcela.getBuscar()+ "%'");
                      }  
                        
        
            Thread.sleep(20000);
             } catch (InterruptedException ex) {
        Thread.currentThread().interrupt();
      }
    }
  }
 
    public telaFecharPedido() {
        initComponents();
        //preencherTabelaParcelas("select *from parcelas order by data");
         new Thread(new Runnable() {
            @Override
            public void run() {
            atualizarTabela();
            }
        }).start();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonEnviarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableParcela = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonPesquisar1 = new javax.swing.JButton();
        jTextFieldPesquisarParcela = new javax.swing.JTextField();
        jButtonParcela = new javax.swing.JButton();

        setClosable(true);

        jTablePedidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePedidos);

        jTextFieldPesquisar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPesquisar.setToolTipText("Pesquisa");
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");

        jButtonEnviarPedido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonEnviarPedido.setText("Enviar Pedido");
        jButtonEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Parcelas Pendentes:");

        jTableParcela.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableParcela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableParcela);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Pedidos Para Entregar:");

        jButtonPesquisar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonPesquisar1.setText("Pesquisar");

        jTextFieldPesquisarParcela.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPesquisarParcela.setToolTipText("Pesquisa");
        jTextFieldPesquisarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarParcelaActionPerformed(evt);
            }
        });

        jButtonParcela.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonParcela.setText("Parcela Paga");
        jButtonParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEnviarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButtonParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnviarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisarParcela, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonParcela)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarPedidoActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        if(jTablePedidos.getSelectedRowCount() != 0){
         resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Enviar o Pedido?");
            if(resposta ==JOptionPane.YES_OPTION){    
                mod.setIdCompra((int) jTablePedidos.getValueAt(jTablePedidos.getSelectedRow(), 0));
                control.Excluir(mod);
                preencherTabelaPedidos("select *from compra order by data");
            }else{ }
        }else{
         JOptionPane.showMessageDialog(null, "Selecione um pedido para a entrega");   
        }
    }//GEN-LAST:event_jButtonEnviarPedidoActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(jTextFieldPesquisar.getText());
        control.Buscar(mod);
        preencherTabelaPedidos("select *from compra where nome like'%" + mod.getPesquisa()+ "%'");
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarParcelaActionPerformed

    private void jButtonParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcelaActionPerformed
        // TODO add your handling code here:
        if(jTableParcela.getSelectedRowCount() != 0){
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "O cliente já realizou o pagamento de R$:"+jTableParcela.getValueAt(jTableParcela.getSelectedRow(), 2).toString()+"?");
        if(resposta ==JOptionPane.YES_OPTION){    
                modParcela.setId((int) jTableParcela.getValueAt(jTableParcela.getSelectedRow(), 0));
                daoParcela.Excluir(modParcela);
                preencherTabelaParcelas("select *from parcelas order by data");
       }else{ }
     }else {
            JOptionPane.showMessageDialog(null, "Selecione uma parcela para efetuar o pagamento da mesma");
        }
    }//GEN-LAST:event_jButtonParcelaActionPerformed

    public void preencherTabelaPedidos(String Sql){
          ArrayList dados = new ArrayList();
          String [] colunas = new String []{"ID","Nome","Valor","Quantidade","Data"};
          conex.conectar();
          conex.executaSql(Sql);        
          try{
              conex.rs.first();
              do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getString("valor"),conex.rs.getInt("quantidade"),conex.rs.getString("data")});
              }while(conex.rs.next());
          }catch(SQLException ex){
              
                      
          }
          modeloTabela modelo = new modeloTabela(dados, colunas);
          
          jTablePedidos.setModel(modelo);
          jTablePedidos.getColumnModel().getColumn(0).setPreferredWidth(200);
          jTablePedidos.getColumnModel().getColumn(0).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(1).setPreferredWidth(365);
          jTablePedidos.getColumnModel().getColumn(1).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(2).setPreferredWidth(315);
          jTablePedidos.getColumnModel().getColumn(2).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(3).setPreferredWidth(340);
          jTablePedidos.getColumnModel().getColumn(3).setResizable(false);
          
          jTablePedidos.getColumnModel().getColumn(4).setPreferredWidth(100);
          jTablePedidos.getColumnModel().getColumn(4).setResizable(false);

          jTablePedidos.getTableHeader().setReorderingAllowed(false);
          jTablePedidos.setAutoResizeMode(jTablePedidos.AUTO_RESIZE_OFF);
          jTablePedidos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.desconecta();
      }

    public void preencherTabelaParcelas(String Sql){
          ArrayList dadosParcela = new ArrayList();
          String [] colunasParcela = new String []{"ID","Nome","Valor","Numero da Parcela","Valor Restante","Valor Total","Data"};
          conex.conectar();
          conex.executaSql(Sql);        
          try{
              conex.rs.first();
              do{
                  dadosParcela.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getString("valor"),conex.rs.getInt("parcelanum"),conex.rs.getString("valorTotalRestante"),conex.rs.getDouble("valorTotal"),conex.rs.getString("data")});
              }while(conex.rs.next());
          }catch(SQLException ex){
              
                      
          }
          modeloTabela modeloParcela = new modeloTabela(dadosParcela, colunasParcela);
          
          
          jTableParcela.setModel(modeloParcela);
          jTableParcela.getColumnModel().getColumn(0).setPreferredWidth(200);
          jTableParcela.getColumnModel().getColumn(0).setResizable(false);
          
          jTableParcela.getColumnModel().getColumn(1).setPreferredWidth(315);
          jTableParcela.getColumnModel().getColumn(1).setResizable(false);
          
          jTableParcela.getColumnModel().getColumn(2).setPreferredWidth(185);
          jTableParcela.getColumnModel().getColumn(2).setResizable(false);
          
          jTableParcela.getColumnModel().getColumn(3).setPreferredWidth(128);
          jTableParcela.getColumnModel().getColumn(3).setResizable(false);
          
          jTableParcela.getColumnModel().getColumn(4).setPreferredWidth(210);
          jTableParcela.getColumnModel().getColumn(4).setResizable(false);
          
          jTableParcela.getColumnModel().getColumn(5).setPreferredWidth(210);
          jTableParcela.getColumnModel().getColumn(5).setResizable(false);

          jTableParcela.getColumnModel().getColumn(6).setPreferredWidth(100);
          jTableParcela.getColumnModel().getColumn(6).setResizable(false);      

          jTableParcela.getTableHeader().setReorderingAllowed(false);
          jTableParcela.setAutoResizeMode(jTableParcela.AUTO_RESIZE_OFF);
          jTableParcela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.desconecta();
      }    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarPedido;
    private javax.swing.JButton jButtonParcela;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableParcela;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPesquisarParcela;
    // End of variables declaration//GEN-END:variables
}
